/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'newuser' at '15/08/05 23:29' with Gradle 2.5
 *
 * @author newuser, @date 15/08/05 23:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
